keys:
  - &admin_laptop age120msgn9wr2d78cmngdkgl3wsg0ftfxauw3slantwh0554h9ayprsdznwxy
  - &admin_desktop age1dk8r7lqc4zrau64z0uqpheevmc2reerzjjwe8pegn6c9rdmjae5stax5zf
  - &yubikey age10apn3gq685qj6nhtk8jxv4hx7tt5ffqvj099nt86keu7glryne0ss6df3c
  - &server_tower age14r54pv5yptseavpj2ggg67psd5qn6cwvywjwua7gare9w2u259zs7580eg
  - &server_assistant age127kdzfp3jyenv32fk0hc7ruyrpc5luw7c3v306f6xs39xj87ppdqrfla4h
  - &server_dashboard age1sxydcql2ht5nqrp0pclj9vxnkr9lfz3s92txlu37u3f7pat9tqts3hzehl
  - &server_ai age1ftyyn6qcvv0v0nz8098sshc33v20gssvjreka6gfs4kl8864kq2scr2a54
creation_rules:
  # Global secrets
  - path_regex: secrets/global\.yaml$
    key_groups:
      - age:
          - *admin_laptop
          - *admin_desktop
          - *yubikey 
          - *server_tower
          - *server_assistant
          - *server_dashboard
          - *server_ai

  # Tower-specific secrets
  - path_regex: secrets/tower\.yaml$
    key_groups:
      - age:
          - *admin_laptop
          - *admin_desktop
          - *yubikey 
          - *server_tower

  # Pi-specific secrets
  - path_regex: secrets/pi\.yaml$
    key_groups:
      - age:
          - *admin_laptop
          - *yubikey 
          - *admin_desktop
          - *server_assistant
          - *server_dashboard
  # Laptop-specific secrets
  - path_regex: secrets/laptop\.yaml$
    key_groups:
      - age:
        - *admin_laptop
        - *yubikey 
        - *admin_desktop
        - *server_ai
